/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package apptest.getpricelabel;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void testGetPriceLabel() {
        App pd = new App();
        assertEquals("Should return a sentence 'The price for coffee mug is 4.00.", String.valueOf("The price for coffee mug is 4.00.\n"), pd.getPriceLabel("coffee mug", 4));
    }
}
